version: '3.9'
services:
  jenkins:
    image: jenkins/jenkins:latest
    privileged: true
    user: root
    container_name: jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /home/vagrant/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
