Vagrant.configure("2") do |config|
  # Конфігурація VM1
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "bento/ubuntu-22.04"
    vm1.vm.network "public_network", ip: "192.168.0.200"
    vm1.vm.hostname = "VM1"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = 2000
      vb.cpus = 2
    end
    # Install docker
    vm1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt update
      sudo apt install -y docker-ce docker-ce-cli containerd.io
      sudo systemctl start docker
      sudo systemctl enable docker
      sudo apt-get update
    SHELL
  end
# Конфігурація VM2
  config.vm.define "vm2" do |vm2|
    vm2.vm.box = "bento/ubuntu-22.04"
    vm2.vm.network "public_network", ip: "192.168.0.201"
    vm2.vm.hostname = "VM2"
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = 3024
      vb.cpus = 2
    end
    # Install docker
    vm2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      sudo apt update
      sudo apt install -y docker-ce docker-ce-cli containerd.io
      sudo systemctl start docker
      sudo systemctl enable docker
    # Install java for worker
      sudo apt-get update
      sudo apt install default-jre -y
      sudo apt install default-jdk -y
    SHELL
  end
end
